### ISSUE TITLE
Error when using "Comment" field with "Choice" in Step Function

### ISSUE THREAD

**Issue by vaib-amz** [aws/amazon-states-language-service#31]
This is related to https://github.com/aws/aws-toolkit-vscode/issues/1165

The Amazon States Language Service incorrectly shows a validation error when specifying a `Comment` field within a `Choice` rule, for example for a `Choice` state as shown below: 

```
...
		  "NotificationChoice": {
			  "Type": "Choice",
			  "Choices": [
				{
					"Comment" : "Indicates that either Apple customer support canceled the subscription or the user upgraded their subscription",	
					"Variable": "$.lambdaresult.notification_type",
					"StringEquals": "CANCEL",
					"Next" : "Cancel"
				},
...
```

This behavior works as expected in the Step Functions console page, but shows the validation errors when using the Amazon States Language Service.

The Choice rule objects in the JSON schema: https://github.com/aws/amazon-states-language-service/blob/master/src/json-schema/partial/choice_state.json need to be updated to allow for the `Comment` field.

**Comment by alanbo** [comment]
I also noticed that "Comment" is not being accepted within "Catch" and "Retry" block.
