### ISSUE TITLE
Invalid state type not validated by vscode

### ISSUE THREAD

**Issue by lialln** [aws/amazon-states-language-service#44]
### Description

When using VS Code to create a state machine using ASL locally, if i have an invalid type of State, i would expect that line of state definition gets highlighted just like the Step Functions Console did.

### Example

| Step Functions Console | VS Code |
| --- | --- |
|<img width="629" alt="Screen Shot 2020-07-17 at 10 52 17 AM" src="https://user-images.githubusercontent.com/68439146/87816153-b84dcc80-c81b-11ea-8149-8b72886a9f5d.png">|<img width="710" alt="Screen Shot 2020-07-17 at 10 52 24 AM" src="https://user-images.githubusercontent.com/68439146/87816166-bd128080-c81b-11ea-8ca9-28d58d0146e8.png">|

**Comment by alanbo** [comment]
I acknowledge the bug. We will look into it.

**Comment by abdelnn** [comment]
Hi there! I realize it's been 3 years, but this has been fixed!

The following definition is now correctly marked as invalid:
```
{
    "Comment": "A Hello World example of the Amazon States Language using Pass states",
    "StartAt": "Hello",
    "States": {
        "Hello": {
            "Type": "Invalid_Task",
            "Resource": "arn:aws:lambda:us-east-1:123456789012:function:serverless",
            "Next": "World"
        },
        "World": {
            "Type": "Task",
            "Resource": "arn:aws:lambda:us-east-1:123456789012:function:serverless",
            "End": true
        }
    }
}
```
<img width="857" alt="Screenshot 2023-06-07 at 5 18 03 PM" src="https://github.com/aws/amazon-states-language-service/assets/107426072/4d538b97-d0fa-4f6e-9dbb-6a09a4be2e8f">
