### ISSUE TITLE
"Parameters" property of State object only allows objects

### ISSUE THREAD

**Issue by mcmathews** [aws/amazon-states-language-service#69]
### Description
I believe there is a bug in the `Parameters` json schema for all the types of State objects.  The schema only supports objects ([as shown here](https://github.com/aws/amazon-states-language-service/blob/dabd384b167ac7d40d3c57b444b0e6ba624f91b7/src/json-schema/partial/common.json#L137-L139)), however I believe that ASL allows any kind of json element in the `Parameters`.  

The [AWS docs on the Amazon States Language](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-amazon-states-language.html) reference [Statelint](https://github.com/awslabs/statelint) as a source of validation, and Statelint's test [show usages of `Parameters` for strings](https://github.com/awslabs/statelint/blob/master/test/pass-with-parameters.json).  I also know from using them, step functions allows `Parameters` to be an array.

It would be great if you could re-evaluate the schema for `Parameters`, as I don't think the current schema is correct.  

Thank you

**Comment by wong-a** [comment]
According to the [Amazon States Language spec](https://states-language.net/spec.html):
> The value of "Parameters" MUST be a Payload Template which is a JSON object, whose input is the result of applying the InputPath to the raw input. If the "Parameters" field is provided, its payload, after the extraction and embedding, becomes the effective input.

The AWS docs don't explicitly state Parameters MUST be a JSON object, though the references are mostly about passing key-value pairs to override the input. https://docs.aws.amazon.com/step-functions/latest/dg/input-output-inputpath-params.html

The service does accept strings and arrays though. The following did pass validation in the UpdateStateMachine API:
```json
{
  "StartAt": "Hello",
  "States": {
    "Hello": {
        "Type": "Pass",
        "Parameters": "hello",
        "End": true
    }
  }
}
```
```json
{
  "StartAt": "Hello",
  "States": {
    "Hello": {
        "Type": "Pass",
        "Parameters": ["1", "2", "3"],
        "End": true
    }
  }
}
```


There are cases where the ASL implementation in Step Functions differs from the language spec. If the AWS documentation doesn't explicitly state strings and arrays are supported, this might be an error. @mcmathews do you have a use case for passing arrays and strings in `Parameters`?

**Comment by mcmathews** [comment]
Yep, your description is consistent with my findings. I don't personally have a use case for passing a string as a `Parameters`, but my team regularly passes arrays for `Parameters`. We use it in a Pass state to set a static array to a field in the execution state (usually for the purpose of implementing default/optional input fields which step functions doesn't support)

**Comment by zaccharles** [comment]
The ASL specification says `Parameters` "MUST be a JSON object". 

Even though Step Functions apparently supports array and string values, maybe it is better to encourage following the spec (one can simply put the string or array inside an object)?

![image](https://user-images.githubusercontent.com/5722738/151363770-9ec497ff-7fb6-4152-b8eb-f74954c881cb.png)
Source: https://states-language.net/#filters
