### ISSUE TITLE
Missing max value for "MaxAttempts" of Retry

### ISSUE THREAD

**Issue by alanbo** [aws/amazon-states-language-service#74]
JSON Schema is missing maximum allowed value for "MaxAttempts" property.

https://github.com/aws/amazon-states-language-service/blob/master/src/json-schema/partial/common.json#L160

It needs to be updated to `99999999`.

**Comment by zaccharles** [comment]
It looks like this issue has been resolved and could be closed.

**Comment by shivlaks** [comment]
resolved via #75
